AWSTemplateFormatVersion: '2010-09-09'
Description: All The Lambdas
Parameters:
  environment:
    Description: Name of the environment for this stack.
    Type: String
    AllowedValues:
      - dev
      - qa
      - stage
      - prod
  product:
    Type: String
  service:
    Type: String
    Default: lambdas
  
Resources:
  slackNotificationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${environment}-${product}-slackNotification-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                  - logs:*
                Resource: "*"
  
  slackNotificationLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${environment}-${product}-slack-notification-lambda
      Code:
        S3Bucket: !ImportValue 
          Fn::Sub:
            ${environment}-${product}-lambda
        S3Key: slackNotification.zip
      Handler: index.lambda_handler
      Role: !GetAtt slackNotificationLambdaRole.Arn
      Runtime: python3.11
      Timeout: 120